config/routes.rb
Rails.application.routes.draw do
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root :to => "home#index"

	namespace :administration do
		devise_for :users, class_name: "User::User"
		root :to => "/administration/dashboard#index"
	end


	namespace :admin do
		devise_for :admin_users, class_name: "Admin::AdminUser",
		:controllers => { :registrations => 'admin/admin_users/registrations',
			:sessions => 'admin/admin_users/sessions', :passwords => 'admin/admin_users/passwords' },
		path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', 
			confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign_up' }

		root :to => "/admin/dashboard#index"
		
		resources :cie_roles do
			collection do
				delete 'destroy_multiple'
			end
		end
		resources :roles do
			collection do
				delete 'destroy_multiple'
			end
		end
		resources :cie_users do
			collection do
				delete 'destroy_multiple'
			end
		end
		resources :parameters
	end
	namespace :registry do
		devise_for :cie_users, class_name: "Registry::CieUser",
		:controllers => {
			:registrations => 'registry/cie_users/registrations',
			:sessions => 'registry/cie_users/sessions', :passwords => 'registry/cie_users/passwords'
		},
		path_names: {
			sign_in: 'login', sign_out: 'logout', password: 'secret',
			confirmation: 'verification',
			unlock: 'unblock', registration: 'register', sign_up: 'sign_up'
			}
		root :to => "/registry/dashboard#index"
		resources :events do
			collection do
				delete 'destroy_multiple'
				get 'load_therapy_room'
				get 'load_therapy_group'
			end
		end
		resources :levels do
			collection do
				delete 'destroy_multiple'
			end
		end
		resources :age_ranges do
			collection do
				delete 'destroy_multiple'
			end
		end
		resources :employees do
			collection do
				get 'load_boss'
				delete 'destroy_multiple'
			end
		end
		resources :employee_positions do
			collection do
				delete 'destroy_multiple'
			end
		end
		resources :therapy_rooms do
			collection do
				delete 'destroy_multiple'
			end
		end
		resources :therapy_types do
			collection do
				delete 'destroy_multiple'
			end
		end
		resources :patients do
			collection do
				delete 'destroy_multiple'
				get 'load_municipalities'
				get :print_invoice, defaults: { format: 'pdf' }
			end
		end
		resources :therapy_groups do
			collection do
				delete 'destroy_multiple'
			end
		end
		resources :patients, param: :id do
			get 'date_schedule'
			get 'medical_record'
			post 'medical_record'
			get :assistance
			get :print_assistance, defaults: { format: 'pdf' }
			get :print_patient, defaults: { format: 'pdf' }
			get :new_assistance_registration
			post :new_assistance_registration
		end
		resources :patients, param: :"id/:assistance_id" do
			get :edit_assistance_registration
			post :edit_assistance_registration
			delete :destroy_assistance
		end
		resources :conditions do
			collection do
				delete 'destroy_multiple'
			end
		end
		resources :date_events
		resource :reports do
			get :group_week_events
			get :employee_month_events
			get :employee_week_events
			get :patient_week_events
			get :room_week_events
			get :group_week_hours
			get :group_week_covered_hours
			get :colaborador_month_covered_hours
			get :_week_covered_hours_employee
			get :print_report, defaults: { format: 'pdf' }
		end
	end
end

app/views/layouts/admin/dashboard_layout.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%=@page_title%></title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<!-- jVectorMap -->
	<script src="/assets/maps/jquery-jvectormap-world-mill-en.js"></script>
	<script src="/assets/maps/jquery-jvectormap-us-aea-en.js"></script>
	<script src="/assets/maps/gdp-data.js"></script>
	<%= favicon_link_tag 'favicon.ico', type: 'image/png' %>
	<%= favicon_link_tag 'favicon.ico'%>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, user-scalable=yes"/>
    <!-- Lesther css -->

    <!-- fuente lato -->
    <link href="https://fonts.googleapis.com/css?family=Lato:300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
    <!-- css -->
    <link rel="stylesheet" type="text/css" href="/assets/default.css" />
    <!-- Smartphones (portrait 240 - 320) -->
    <link rel="stylesheet" href="/assets/s240_base.css" type="text/css" media="only screen and (min-width : 240px)" />
    <link rel="stylesheet" href="/assets/s240_body.css" type="text/css" media="only screen and (min-width : 240px)" />

    <!-- js -->
   	<script src="/assets/show_hide.js"></script>
</head>

<body class="nav-md footer_fixed">
	<div class="container body">
		<div class="main_container">
			<div class="col-md-3 left_col menu_fixed">
				<div class="left_col scroll-view">
					<div class="navbar nav_title" style="border: 0;">
						<div class="nav toggle"><a id="menu_toggle"></a></div>
						
					</div>

					<div class="clearfix"></div>

					<!-- menu profile quick info -->
					<div class="profile clearfix">


						<div class="profile_pic_container" alt="" title="">
									
							<div class="notification_sidebar">
								<li class="dropdown">
	                                
	                            </li>
							</div>
							


                         	<div class="profile_pic circle" style="background-image: url('<%=current_cie_user.image_source("avatar")%>');"></div>
                        </div>
                        <div class="profile_info">
                            <span class="name_profile"><%=link_to current_cie_user.name.to_s, edit_admin_admin_user_registration_path(current_cie_user.id)%></span>
                            <span class="data_profile">ADMINISTRADOR</span>
                        </div>

					</div>
					<!-- /menu profile quick info -->

					<br />
					<!-- sidebar menu -->
					
					<!-- /sidebar menu -->
					<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                    	<div class="menu_section">


							<ul class="nav side-menu" style="display: block;">
								<li class="<%= current_page(Registry::DashboardController)%>">
		                        	<a href="<%=session_root_path%>">
		                        		<i class="dashboard_icon icon"></i> Dashboard
		                        	</a>
		                        </li>
								
								<li><a><i class="rrhh_icon icon"></i>Roles</a>
									<ul class="nav child_menu">
										<li class="<%= current_page(Admin::CieRolesController)%>"><%=link_to "Usuario de Registro", admin_cie_roles_path%></li>
									</ul>
								</li>
								<li><a><i class="registry_icon icon"></i>Registro</a>
									<ul class="nav child_menu">
										<li class="<%= current_page(Admin::CieUsersController)%>"><%=link_to "Usuarios", admin_cie_users_path%></li>
										<li class="<%= current_page(Admin::ParametersController)%>"><%=link_to "Parámetros", admin_parameters_path%></li>
									</ul>
								</li>
							</ul>
						</div>
					</div>

					<script>
						$(".current-page").parent().parent().addClass("active");
						$(".current-page").parent().css("display","block");
					</script>
					<!-- /menu footer buttons -->
					<%=footer_menu%>
					<!-- /menu footer buttons -->
				</div>
			</div>

			<!-- top navigation -->
			<%=top_nav_menu%>
			<!-- /top navigation -->

			<!-- page content -->
			<%=yield%>
			<!-- /page content -->

			<!-- footer content -->
			<footer>
				<div class="logo_cie_container circle">
                    <div class="logo_cie icon"></div>
                </div>
                <div class="pull-right">
                    CIE powered by <a href="http://digitech.net.ni/digitech/" target="_blank">Digitech</a>
                </div>
                <div class="clearfix"></div>
			</footer>
			<!-- /footer content -->
		</div>
	</div>
</body>
</html>

app/views/layouts/admin/login_layout.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%=@page_title%></title>
	<%= csrf_meta_tags %>

	<%= favicon_link_tag 'favicon.ico', type: 'image/png' %>
	<%= favicon_link_tag 'favicon.ico'%>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, user-scalable=yes"/>
	<!-- jquery librery -->

	<!-- google font -->
    <!-- fuente lato -->
    <link href="https://fonts.googleapis.com/css?family=Lato:300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

	<!-- screens -->
    <!-- css -->
    <link rel="stylesheet" type="text/css" href="/assets/default.css" />
    <!-- Smartphones (portrait 240 - 320) -->
    <link rel="stylesheet" href="/assets/s240_base.css" type="text/css" media="only screen and (min-width : 240px)" />
    <link rel="stylesheet" href="/assets/s240_body.css" type="text/css" media="only screen and (min-width : 240px)" />
    <link rel="stylesheet" href="/assets/s240_update.css" type="text/css" media="only screen and (min-width : 240px)" />
    <link rel="stylesheet" href="/assets/s240_login.css" type="text/css" media="only screen and (min-width : 240px)" />


    <!-- js -->
    <script src="/assets/show_hide.js"></script>
</head>
<body class="login">
	<%=devise_error_messages!%>
	<div class="container_login">
		<div class="middle_container">
			<div class="middle_cell">
				
				<div class="login_wrap text-center">
					<div class="container_title_login_form">
						<div class="title_login_form inline_divs">
							<div class="icon_register">
								<svg class="svg-icon" viewBox="0 0 20 	20">
									<path fill="none" d="M19.521,7.267c-0.144-0.204-0.38-0.328-0.631-0.328h-3.582l-0.272-1.826c-0.055-0.379-0.379-0.656-0.76-0.656
									H9.802l-0.39-0.891c-0.123-0.279-0.399-0.46-0.704-0.46H1.11c-0.222,0-0.434,0.096-0.58,0.264C0.385,3.537,0.319,3.76,0.349,3.981
									l1.673,12.243c0,0,0,0,0,0.002v0.004c0.015,0.113,0.06,0.213,0.119,0.303c0.006,0.009,0.006,0.023,0.012,0.033
									c0.012,0.016,0.033,0.024,0.046,0.04c0.054,0.065,0.114,0.118,0.185,0.161c0.027,0.018,0.051,0.035,0.078,0.048
									c0.099,0.045,0.206,0.078,0.32,0.078h0.002l0,0h13.03c0.323,0,0.611-0.201,0.722-0.505l3.076-8.416
									C19.698,7.735,19.663,7.474,19.521,7.267z M8.203,4.644l0.391,0.889c0.123,0.279,0.399,0.461,0.704,0.461h4.315l0.141,0.944H5.859
									c-0.323,0-0.611,0.201-0.723,0.505l-2.011,5.505L1.992,4.644H8.203z M15.276,15.356H3.882l2.515-6.879H17.79L15.276,15.356z"></path>
								</svg>
							</div>
							<div class="">
								Administración
							</div>
						</div>
					</div>

					<div class="form_login">
						<div class="description_title_login_form">
							Por favor ingrese sus datos
						</div>
						<!-- form -->
						<div class="form_container_login">
							<%= yield%>
						</div>
					</div>
					<!-- footer min height -->
					<div class="min_height_footer">
						©2018 All Rights Reserved. Digitech.
						<!-- <br> -->
						Privacy and Terms
					</div>
				</div>

			</div>
		</div>
		
		<!-- bottom -->
		<div class="footer_login">
			©2018 All Rights Reserved. Digitech.
			<!-- <br> -->
			Privacy and Terms
		</div>
		
	</div>
</body>
</html>