config/routes.rb
Rails.application.routes.draw do
	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
	root :to => "home#index"

	namespace :administration do
		devise_for :users, class_name: "User::User"
		root :to => "/administration/dashboard#index"
	end


	namespace :admin do
		devise_for :admin_users, class_name: "Admin::AdminUser",
		:controllers => { :registrations => 'admin/admin_users/registrations',
			:sessions => 'admin/admin_users/sessions', :passwords => 'admin/admin_users/passwords' },
		path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', 
			confirmation: 'verification', unlock: 'unblock', registration: 'register', sign_up: 'sign_up' }

		root :to => "/admin/dashboard#index"
		
		resources :cie_roles do
			collection do
				delete 'destroy_multiple'
			end
		end
		resources :roles do
			collection do
				delete 'destroy_multiple'
			end
		end
		resources :cie_users do
			collection do
				delete 'destroy_multiple'
			end
		end
		resources :parameters
	end
	namespace :registry do
		devise_for :cie_users, class_name: "Registry::CieUser",
		:controllers => {
			:registrations => 'registry/cie_users/registrations',
			:sessions => 'registry/cie_users/sessions', :passwords => 'registry/cie_users/passwords'
		},
		path_names: {
			sign_in: 'login', sign_out: 'logout', password: 'secret',
			confirmation: 'verification',
			unlock: 'unblock', registration: 'register', sign_up: 'sign_up'
			}
		root :to => "/registry/dashboard#index"
		resources :events do
			collection do
				delete 'destroy_multiple'
				get 'load_therapy_room'
				get 'load_therapy_group'
			end
		end
		resources :levels do
			collection do
				delete 'destroy_multiple'
			end
		end
		resources :age_ranges do
			collection do
				delete 'destroy_multiple'
			end
		end
		resources :employees do
			collection do
				get 'load_boss'
				delete 'destroy_multiple'
			end
		end
		resources :employee_positions do
			collection do
				delete 'destroy_multiple'
			end
		end
		resources :therapy_rooms do
			collection do
				delete 'destroy_multiple'
			end
		end
		resources :therapy_types do
			collection do
				delete 'destroy_multiple'
			end
		end
		resources :patients do
			collection do
				delete 'destroy_multiple'
				get 'load_municipalities'
				get :print_invoice, defaults: { format: 'pdf' }
			end
		end
		resources :therapy_groups do
			collection do
				delete 'destroy_multiple'
			end
		end
		resources :patients, param: :id do
			get 'date_schedule'
			get 'medical_record'
			post 'medical_record'
			get :assistance
			get :print_assistance, defaults: { format: 'pdf' }
			get :print_patient, defaults: { format: 'pdf' }
			get :new_assistance_registration
			post :new_assistance_registration
		end
		resources :patients, param: :"id/:assistance_id" do
			get :edit_assistance_registration
			post :edit_assistance_registration
			delete :destroy_assistance
		end
		resources :conditions do
			collection do
				delete 'destroy_multiple'
			end
		end
		resources :date_events
		resource :reports do
			get :group_week_events
			get :employee_month_events
			get :employee_week_events
			get :patient_week_events
			get :room_week_events
			get :group_week_hours
			get :group_week_covered_hours
			get :colaborador_month_covered_hours
			get :_week_covered_hours_employee
			get :print_report, defaults: { format: 'pdf' }
		end
	end
end

app/models/registry.rb
module Registry
  def self.table_name_prefix
    'registry_'
  end
end

app/models/registry/age_range.rb
# == Schema Information
#
# Table name: registry_age_ranges
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  min_age     :integer
#  max_age     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Registry::AgeRange < ApplicationRecord
	before_destroy :check_for_level

	has_many :registry_levels, :class_name => "Registry::Level", 
		foreign_key: "facturacion_age_range_id", :inverse_of => :registry_age_range

	include AvoidDestroyReferencesUtility 

	def self.security_name
		"Rangos de Edad"
	end

	def display_name
		"#{name} (#{min_age} - #{max_age}) años"
	end

	validates_presence_of :name, :description, :max_age, :min_age
	validates_numericality_of :max_age, :min_age

	private
	def check_for_level
		check_for_relation(registry_levels, "Área")
	end
end

app/models/registry/cie_user.rb
# == Schema Information
#
# Table name: registry_cie_users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  avatar                 :string
#  name                   :string
#  is_evaluator           :boolean
#

class Registry::CieUser < ApplicationRecord
	mount_uploader :avatar, AvatarUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  	
  	has_and_belongs_to_many :admin_cie_roles, :class_name => "Admin::CieRole",
  		:join_table => :registry_cie_users_registry_cie_roles, foreign_key: "registry_cie_user_id",
  		association_foreign_key: "admin_cie_role_id"

    validates_presence_of :admin_cie_roles
    validates_uniqueness_of :email
  	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	include UserModelUtility
	def self.security_name
		"Usuario de Registro"
	end

  def display_name
    self.name
  end
end

app/models/registry/condition.rb
# == Schema Information
#
# Table name: registry_conditions
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Registry::Condition < ApplicationRecord
	before_destroy :check_for_patient

	validates_presence_of :name, :description

	has_many :registry_patients, :class_name => "Registry::Patient", 
		foreign_key: "registry_condition_id", :inverse_of => :registry_condition

	include AvoidDestroyReferencesUtility 
	def self.security_name
		"Condición"
	end
	def display_name
		name
	end

	private
	def check_for_patient
		check_for_relation(registry_patients, "Paciente")
	end
end

app/models/registry/date_event.rb
# == Schema Information
#
# Table name: registry_date_events
#
#  id                  :integer          not null, primary key
#  name                :string
#  description         :text
#  start_time          :datetime
#  end_time            :datetime
#  color               :string
#  date_event_type     :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  registry_patient_id :integer
#  billable            :boolean
#  comments            :text
#  completed_date      :boolean
#  child_guardian      :string
#  phone_number        :string
#  child_name          :string
#

class Registry::DateEvent < ApplicationRecord
	attr_accessor :date_range

	has_many :registry_date_event_employees, :class_name => "Registry::DateEventEmployee", 
		foreign_key: "registry_date_event_id", :inverse_of => :registry_date_event, :dependent => :destroy

	has_many :registry_employees, :through => :registry_date_event_employees, 
		:class_name => "Registry::Employee", :inverse_of => :registry_date_event

	belongs_to :registry_patient, :class_name => "Registry::Patient", :inverse_of => :registry_date_events, optional: true
	
	accepts_nested_attributes_for :registry_date_event_employees,
		:allow_destroy => true,
		:reject_if     => :all_blank
		
	def color_map
		[
			["Plata","#efefef"],
			["Gris","#c4c4c4"],
			["Negro","#000000"],
			["Marrón","#f1e3d1"],
			["Amarillo","#fffcdb"],
			["Oliva","#d9d9b2"],
			["Lima","#b2ffb2"],
			["Verde","#b2d9b2"],
			["Aqua","#ccffff"],
			["Verde Azulado","#b6daff"],
			["Azul","#0c84ff"],
			["Fucsia","#e0b6ea"],
			["Púrpura","#7300a9"],	
			['Rojo','#ffcccc'], 
			['Naranja','#ff7e00'], 
			['Cyan','#ccebf8'], 
			['Rosado','#f95aff'],
		]
	end

	def text_color_hash
		{
			"#efefef"=>"#878787",
			"#c4c4c4"=>"#888888",
			"#000000"=>"#4e4e4e",
			"#f1e3d1"=>"#ea6666",
			"#fffcdb"=>"#be8e50",
			"#d9d9b2"=>"#cdb200",
			"#b2ffb2"=>"#7e7e21",
			"#b2d9b2"=>"#629f62",
			"#ccffff"=>"#4f954f",
			"#b6daff"=>"#229c9c",
			"#0c84ff"=>"#c0c0ef",
			"#e0b6ea"=>"#6d1f81",
			"#7300a9"=>"#6f09b6",	
			'#ffcccc'=>"#b14f4f", 
			'#ff7e00'=>"#c37f3d", 
			'#ccebf8'=>"#009bdb", 
			'#f95aff'=>"#db4ac8",
		}
	end

	def start_time_formatted
		start_time.strftime("%d/%m/%Y %T")
	end

	def self.security_name
		"Citas"
	end
	def display_name
		name
	end

	def event_type_map 
		[['Cita','Cita'], ['Evaluación','Evaluación']]
	end
  	
  	def all_day_event?
  		self.end_time = self.end_time.present? ? self.end_time : self.start_time.midnight
    	self.start_time == self.start_time.midnight && self.end_time.present? && self.end_time == self.end_time.midnight ? true : false
	end
end

app/models/registry/date_event_employee.rb
# == Schema Information
#
# Table name: registry_date_event_employees
#
#  id                     :integer          not null, primary key
#  registry_date_event_id :integer
#  registry_employee_id   :integer
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class Registry::DateEventEmployee < ApplicationRecord
  belongs_to :registry_date_event, :class_name => "Registry::DateEvent", :inverse_of => :registry_date_event_employees
  belongs_to :registry_employee, :class_name => "Registry::Employee", :inverse_of => :registry_date_event_employees
end

app/models/registry/department.rb
# == Schema Information
#
# Table name: registry_departments
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Registry::Department < ApplicationRecord
	has_many :registry_municipalities, :class_name => "Registry::Municipality", 
		foreign_key: "registry_department_id", :inverse_of => :registry_department

	def display_name
		self.name
	end
	def self.security_name
		"Departamento"
	end
end

app/models/registry/employee.rb
# == Schema Information
#
# Table name: registry_employees
#
#  id                            :integer          not null, primary key
#  first_name                    :string
#  last_name                     :string
#  birth_date                    :date
#  registry_employee_position_id :integer
#  start_date                    :date
#  active                        :boolean
#  avatar                        :string
#  created_at                    :datetime         not null
#  updated_at                    :datetime         not null
#  email                         :string
#  boss_id                       :integer
#  registry_therapy_group_id     :integer
#

class Registry::Employee < ApplicationRecord

	mount_uploader :avatar, AvatarUploader
	
	before_destroy :check_for_event

	# before_save :check_for_coordinador
	
 	belongs_to :registry_employee_position, :class_name => "Registry::EmployeePosition", :inverse_of => :registry_employees

 	#belongs_to :boss, :class_name => "Registry::Employee"
 	belongs_to :registry_therapy_group, :foreign_key => "registry_therapy_groups_id", :class_name => "Registry::TherapyGroup", :inverse_of => :registry_employees, optional: true

 	has_many :registry_events, :class_name => "Registry::Event", 
		foreign_key: "registry_employee_id", :inverse_of => :registry_employee

	has_many :registry_date_event_employees, :class_name => "Registry::DateEventEmployee", 
		foreign_key: "registry_employee_id", :inverse_of => :registry_employee

	has_one :registry_date_event, :through => :registry_date_event_employees, 
		:class_name=> "Registry::DateEvent", :inverse_of => :registry_employees

	has_many :registry_patient_assistances, :class_name => "Registry::PatientAssistance", 
		foreign_key: "registry_employee_id", :inverse_of => :registry_employee

		has_many :registry_patient_assistances_delivered, :class_name => "Registry::PatientAssistance", 
		foreign_key: "employee_who_delivers_id", :inverse_of => :registry_employee

		has_many :registry_patient_assistances_received, :class_name => "Registry::PatientAssistance", 
		foreign_key: "employee_who_receives_id", :inverse_of => :registry_employee

	scope :employee, -> (employee) { where(:id => employee)}
  	scope :employee_position, -> (employee_position) { where(:registry_employee_position => employee_position)}
  	scope :active, -> (active) { where(:active => active)}

	def self.employers_from_group(groupID)
		sql = "select re.id, re.first_name, re.last_name from registry_employees as re, registry_therapy_groups as tg where re.registry_therapy_group_id = tg.id and tg.id=#{groupID};"
		data = ActiveRecord::Base.connection.execute(sql)
		# data = Registry::Employee.joins(:registry_therapy_group).distinct.select('registry_employees.*').where('registry_therapy_groups_id = ?', groupID)	
		

	end
	def self.id(groupID)
		sql = "select re.id from registry_employees as re, registry_therapy_groups as tg where re.registry_therapy_group_id = tg.id and tg.id=#{groupID};"
		data = ActiveRecord::Base.connection.execute(sql)
		# data = Registry::Employee.joins(:registry_therapy_group).distinct.select('registry_employees.*').where('registry_therapy_groups_id = ?', groupID)	
	end

    #Calculo de Horas Asignadas
	def self.HorasAsignadas(start_date,end_date,emID, groupID)
		sql = "select count(o.id) as Horas from registry_occurrences as o 
		inner join registry_events as 
		e on (o.registry_event_id=e.id) 
		inner join registry_employees as em
		on (e.registry_employee_id=em.id)
		inner join registry_therapy_groups as te 
		on(em.registry_therapy_group_id=te.id) where o.date between '#{start_date}'
		and '#{end_date}' and e.registry_employee_id=#{emID} and em.registry_therapy_group_id=#{groupID}"
		data = ActiveRecord::Base.connection.execute(sql)
		
	   # data = Registry::Employee.joins(:registry_therapy_group).distinct.select('registry_employees.*').where('registry_therapy_groups_id = ?', groupID)	
	end
   #Calculo de Horas Cumplidas
	def self.HorasCumplida(start_date,end_date,emID, groupID)
		sql = "select count(pa.id) as Horas_Cumplidas from registry_patient_assistances as pa
		inner join registry_employees 
		as e on(pa.employee_who_receives_id=e.id) 
		inner join registry_employee_positions as ep
		on(e.registry_employee_position_id=ep.id) 
		where assistance_date between '#{start_date}' and '#{end_date}'
		and pa.employee_who_receives_id=#{emID} 
		and e.registry_therapy_group_id=#{groupID} "
		data = ActiveRecord::Base.connection.execute(sql)
		# data = Registry::Employee.joins(:registry_therapy_group).distinct.select('registry_employees.*').where('registry_therapy_groups_id = ?', groupID)	
	end


	include Filterable

	include AvoidDestroyReferencesUtility 
	include PersonalData 
 	def self.security_name
		"Colaboradores"
	end
	
	def self.get_coordinadores
		Registry::Employee.where(:registry_employee_position_id => Registry::EmployeePosition.where(:name => "Coordinador").first.id)
	end

 	def start_date_formatted
		if !self.new_record?
			start_date.strftime("%d/%m/%Y")
		else
			start_date
		end
	end

	def display_name
		"#{first_name} #{last_name}"
	end

	validates_presence_of :start_date, :registry_employee_position_id

	private
	def check_for_event
		check_for_relation(registry_events, "Evento")
	end
	def check_for_coordinador#(selfPostitionChanged=false)
		employee_therapy_group_related = Registry::Employee.where(:registry_therapy_group_id => self.registry_therapy_group_id, 
				:registry_employee_position_id => Registry::EmployeePosition.where(:name => "Coordinador").first.id)
		if self.registry_employee_position.name == "Coordinador"
			self_employee_relation = employee_therapy_group_related.where(:id => self.id) if self.id.present? 
			if employee_therapy_group_related.present? && self_employee_relation.blank?
				errors.add(:base,"El grupo de terapia #{self.registry_therapy_group.display_name} ya posee un coordinador asociado.")
			end	
		else
			if employee_therapy_group_related.present?
				employee_record = employee_therapy_group_related.where(:id => self.id)
				if employee_record.present? 
					if Registry::Employee.where(:registry_therapy_group_id => self.registry_therapy_group_id, :boss_id => self.id).present?
						errors.add(:base,"El colaborador a modificar es coordinador de el grupo de terapia #{self.registry_therapy_group.display_name}. Existen colaboradores a su cargo, modifique los colaboradores asociados")
					else
						errors.add(:base,"El colaborador a modificar es coordinador de el grupo de terapia #{self.registry_therapy_group.display_name}. Debe existir un coordinador para el grupo de terapia")
					end
				else
					errors.add(:base,"El grupo de terapia #{self.registry_therapy_group.display_name} tiene un coordinador asociado, seleccione el coordinador para poder proceder.") if self.boss_id.blank?
				end
			else
				errors.add(:base,"El grupo de terapia #{self.registry_therapy_group.display_name} NO tiene un coordinador asociado, cree el coordinador para poder proceder.")
			end
		end
		if self.errors.present?
			raise CustomExceptions::SpecialException
		end
	end
end

app/views/layouts/registry/dashboard_layout.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%=@page_title%></title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<!-- jVectorMap -->
	<script src="/assets/maps/jquery-jvectormap-world-mill-en.js"></script>
	<script src="/assets/maps/jquery-jvectormap-us-aea-en.js"></script>
	<script src="/assets/maps/gdp-data.js"></script>
	<%= favicon_link_tag 'favicon.ico', type: 'image/png' %>
	<%= favicon_link_tag 'favicon.ico'%>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, user-scalable=yes"/>
    <!-- Lesther css -->

    <!-- fuente lato -->
    <link href="https://fonts.googleapis.com/css?family=Lato:300,300i,400,400i,700,700i,900,900i" rel="stylesheet">
    <!-- css -->
    <link rel="stylesheet" type="text/css" href="/assets/default.css" />
    <!-- Smartphones (portrait 240 - 320) -->
    <link rel="stylesheet" href="/assets/s240_base.css" type="text/css" media="only screen and (min-width : 240px)" />
    <link rel="stylesheet" href="/assets/s240_body.css" type="text/css" media="only screen and (min-width : 240px)" />

    <!-- js -->
   	<script src="/assets/show_hide.js"></script>
</head>

<body class="nav-md footer_fixed">
	<div class="container body">
		<div class="main_container">
			<div class="col-md-3 left_col menu_fixed">
				<div class="left_col scroll-view">
					<div class="navbar nav_title" style="border: 0;">
						<div class="nav toggle"><a id="menu_toggle"></a></div>
						
					</div>

					<div class="clearfix"></div>

					<!-- menu profile quick info -->
					<div class="profile clearfix">


						<div class="profile_pic_container" alt="" title="">
									
							<div class="notification_sidebar">
								<%=alerts_menu%>
							</div>
							


                         	<div class="profile_pic circle" style="background-image: url('<%=current_cie_user.image_source("avatar")%>');"></div>
                        </div>
                        <div class="profile_info">
                            <span class="name_profile"><%=link_to current_cie_user.name.to_s, edit_registry_cie_user_registration_path(current_cie_user.id)%></span>
                            <span class="data_profile">Registro</span>
                        </div>

					</div>
					<!-- /menu profile quick info -->

					<br />
					<!-- sidebar menu -->
					
					<!-- /sidebar menu -->
					<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
                    	<div class="menu_section">
							<ul class="nav side-menu" style="display: block;">
		                        <li class="<%= current_page(Registry::DashboardController)%>">
		                        	<a href="<%=session_root_path%>">
		                        		<i class="dashboard_icon icon"></i> Dashboard
		                        	</a>
		                        </li>
		                        <li><a><i class="registry_icon icon"></i>Registro</a>
		                            <ul class="nav child_menu">
		                                <li class="<%= current_page(Registry::PatientsController)%>">
		                                	<%=link_to "Pacientes", registry_patients_path %>
		                                </li>
		                                <li class="<%= current_page(Registry::ConditionsController)%>">
		                                	<%=link_to "Condiciones Médicas", registry_conditions_path%>
		                                </li>
		                            </ul>
		                        </li>
		                        <li><a><i class="heart_icon icon"></i>Terapias</a>
		                            <ul class="nav child_menu">
		                                <li class="<%= current_page(Registry::TherapyTypesController)%>">
		                                	<%=link_to "Tipos de Terapia", registry_therapy_types_path%>
		                                </li>
		                                <li class="<%= current_page(Registry::AgeRangesController)%>">
		                                	<%=link_to "Rangos de Edad", registry_age_ranges_path%>
		                                </li>
		                                <li class="<%= current_page(Registry::LevelsController)%>">
		                                	<%=link_to "Áreas", registry_levels_path%>
		                                </li>
		                                <li class="<%= current_page(Registry::TherapyRoomsController)%>">
		                                	<%=link_to "Salones", registry_therapy_rooms_path%>
		                                </li>
		                                <li class="<%= current_page(Registry::TherapyGroupsController)%>">
		                                	<%=link_to "Grupo de Terapia", registry_therapy_groups_path%>
		                                </li>
		                            </ul>
		                        </li>
		                        <li><a><i class="rrhh_icon icon"></i>RRHH</a>
		                            <ul class="nav child_menu">
		                                <li class="<%= current_page(Registry::EmployeesController)%>">
		                                	<%=link_to "Colaboradores", registry_employees_path%>
		                                </li>
										<li class="<%= current_page(Registry::EmployeePositionsController)%>">
											<%=link_to "Cargos", registry_employee_positions_path%>
										</li>
		                            </ul>
		                        </li>
		                        <li><a><i class="calendar_icon icon"></i>Calendario</a>
		                            <ul class="nav child_menu	">
		                                <li class="<%= current_page(Registry::EventsController)%>">
		                                	<%=link_to "Agenda", registry_events_path%>
		                                </li>
		                            </ul>
		                        </li>
		                        <li><a><i class="calendar_icon icon"></i>Reportes</a>
		                            <ul class="nav child_menu	">
		                                <li class="<%= current_page(Registry::ReportsController)%>">
		                                	<%=link_to "Horario Grupal", group_week_events_registry_reports_path%>
		                                </li>
		                                <li class="<%= current_page(Registry::ReportsController)%>">
		                                	<%=link_to "Horario Mes", employee_month_events_registry_reports_path%>
		                                </li>
		                                <li class="<%= current_page(Registry::ReportsController)%>">
		                                	<%=link_to "Horario Semana", employee_week_events_registry_reports_path%>
		                                </li>
		                                <li class="<%= current_page(Registry::ReportsController)%>">
		                                	<%=link_to "Horario Sem/ Paciente", patient_week_events_registry_reports_path%>
		                                </li>
		                                <li class="<%= current_page(Registry::ReportsController)%>">
		                                	<%=link_to "Horario Salón", room_week_events_registry_reports_path%>
		                                </li>
		                                <li class="<%= current_page(Registry::ReportsController)%>">
		                                	<%=link_to "Horas / Colaborador", group_week_hours_registry_reports_path%>
		                                </li>
		                                <li class="<%= current_page(Registry::ReportsController)%>">
		                                	<%=link_to "Horas Cubiertas / Colaborador", group_week_covered_hours_registry_reports_path%>
		                                </li>
		                                <li class="<%= current_page(Registry::ReportsController)%>">
		                                	<%=link_to "Horas Mensuales / Coordinador", colaborador_month_covered_hours_registry_reports_path%>
		                                </li>
		                            </ul>
		                        </li>
		                    </ul>
						</div>
					</div>

					<script>
						$(".current-page").parent().parent().addClass("active");
						$(".current-page").parent().css("display","block");
					</script>
					<!-- /menu footer buttons -->
					<%=footer_menu%>
					<!-- /menu footer buttons -->
				</div>
			</div>

			<!-- top navigation -->
			<%=top_nav_menu%>
			<!-- /top navigation -->

			<!-- page content -->
			<%=yield%>
			<!-- /page content -->

			<!-- footer content -->
			<footer>
				<div class="logo_cie_container circle">
                    <div class="logo_cie icon"></div>
                </div>
                <div class="pull-right">
                    CIE powered by <a href="http://digitech.net.ni/digitech/" target="_blank">Digitech</a>
                </div>
                <div class="clearfix"></div>
			<!-- /footer content -->
		</div>
	</div>
	<div class="container spinner" style="position: absolute; z-index: 2147483647; top: 0px; bottom: 0px; display:none">
		<div class="row" style="position: relative; height: 100%; width: 100%;">
			<div id="loader">
	    		<div class="dot"></div>
				<div class="dot"></div>
				<div class="dot"></div>
				<div class="dot"></div>
				<div class="dot"></div>
				<div class="dot"></div>
				<div class="dot"></div>
				<div class="dot"></div>
				<div class="lading"></div>
			</div>
		</div>
	</div>
</body>
</html>